### ISSUE TITLE
Autoload problem

### ISSUE THREAD

**Issue by sananguliyev** [MadnessCODE/Voluum#1]
There no autoload configuration when installing the library with the composer. So I think that you should change it. 

**Error:**
`Class 'MadnessCODE\Voluum\Client\API' not found`

https://github.com/MadnessCODE/Voluum/blob/master/composer.json

https://github.com/MadnessCODE/Voluum/blob/1.0/composer.json
https://github.com/MadnessCODE/Voluum/blob/v1.0.0/composer.json

```
"autoload": {
        "psr-0": {
            "Voluum": "src/"
        }
```

**Comment by MadnessCODE** [comment]
Thanks for letting me know :)
Try now :)
