### ISSUE TITLE
Help, this is not an issue

### ISSUE THREAD

**Issue by improve-ar** [MadnessCODE/Voluum#2]
Hi, i dont understand this endpoint of the api:
"/reports/conversions"

in the docs says required params are "from" and "columns".
I do this:

```
$result = $report_api->get('report/conversions', [
        "from" => date("Y-m-d"),
        "columns" => ["campaign"]
    ]);
```
and the error: Request parameter missing

Here the url to exact endpoint of the docs: https://developers.voluum.com/#!/Reports/get_report_conversions

**Comment by MadnessCODE** [comment]
Hi, try this:
```
$result = $report_api->get('report/conversions', [
        "from" => "2018-05-14T00:00:00Z",
        "to" => "2018-05-14T12:00:00Z",
        "columns" => "campaign",
	"limit" => 10
    ]);
```
